# fly.toml app configuration file generated for voice-bot-biraj-rocks on 2025-01-20T19:59:39+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'voice-bot-biraj-rocks'
primary_region = 'bom'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[services]]
  protocol = 'udp'
  internal_port = 8080

  [[services.ports]]
    port = 8080

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
